Lab1
Ppppppe/hoopersbase pull request #1
Opened 2022-10-10 12:01 UTC by Ppppppe

2022-10-10 12:36 UTC, BakasaRus requested changes

2022-10-10 12:36 UTC, BakasaRus commented on index.html
> +    </head>
Не хватает ключевых слов

2022-10-10 12:36 UTC, BakasaRus commented on index.html
> +                    <a href="https://github.com/swar/nba_api">Тык</a>
Ссылку лучше открывать в новой вкладке

2022-10-11 22:20 UTC, Ppppppe commented on index.html
> +    </head>
Добавил ключевые слова

2022-11-15 16:03 UTC, merged